"""
 Unthinkable IT Software Install Agent
=========================
A chat-based tool that lets users request software installations.
Uses Ollama (local AI) for friendly responses.

HOW TO RUN:
    pip install flask paramiko requests
    python app.py
    Then open: http://localhost:5000
"""

from flask import Flask, request, jsonify, session, send_file
import json, os, io, re, requests, paramiko

app = Flask(__name__)
app.secret_key = "change-this-to-something-secret-123"   # ← Change this!

# ─────────────────────────────────────────────────────────
#  SETTINGS  (change these if needed)
# ─────────────────────────────────────────────────────────
OLLAMA_URL   = "http://localhost:11434/api/generate"
OLLAMA_MODEL = "llama3.2"          # Whatever model you have pulled in Ollama
USE_OLLAMA   = True                # Set to False to skip Ollama (plain text only)
CONFIG_FILE  = "config.json"       # Software list lives here

# ─────────────────────────────────────────────────────────
#  LOAD SOFTWARE CONFIG
# ─────────────────────────────────────────────────────────
def load_config():
    """Load the software list from config.json"""
    path = os.path.join(os.path.dirname(__file__), CONFIG_FILE)
    with open(path) as f:
        return json.load(f)

# ─────────────────────────────────────────────────────────
#  OLLAMA HELPER
# ─────────────────────────────────────────────────────────
def ai_say(plain_text: str) -> str:
    """
    Ask Ollama to make a message sound friendlier.
    If Ollama is not running, returns the plain text as-is.
    """
    if not USE_OLLAMA:
        return plain_text
    try:
        resp = requests.post(
            OLLAMA_URL,
            json={
                "model": OLLAMA_MODEL,
                "prompt": (
                    "You are a Hard IT support assistant. "
                    "Rephrase the following message to sound friendly and professional. "
                    "Keep it SHORT (2-3 sentences max). Do not add extra information. "
                    "Message: " + plain_text
                ),
                "stream": False,
            },
            timeout=20,
        )
        result = resp.json().get("response", "").strip()
        return result if result else plain_text
    except Exception:
        return plain_text   # Ollama not running — use plain text

# ─────────────────────────────────────────────────────────
#  SCRIPT GENERATOR
# ─────────────────────────────────────────────────────────
def make_sh_script(software_key: str, config: dict) -> str:
    """Generate a .sh installation script for a given software."""
    sw = config["software"][software_key]
    lines = [
        "#!/bin/bash",
        "#" + "=" * 50,
        f"# Install script: {sw['display_name']}",
        f"# Description:    {sw['description']}",
        "# Generated by:   IT Install Agent",
        "#" + "=" * 50,
        "",
        "set -e   # Stop script if any command fails",
        "echo '🚀 Starting installation...'",
        "",
    ]
    # Optional: pre-install steps (e.g. apt update)
    for step in sw.get("pre_install", []):
        lines.append(step)
    if sw.get("pre_install"):
        lines.append("")

    # Main install commands
    for cmd in sw["commands"]:
        lines.append(f"echo '➤ Running: {cmd}'")
        lines.append(cmd)
    lines.append("")

    # Optional: post-install steps (e.g. enable service)
    for step in sw.get("post_install", []):
        lines.append(step)
    if sw.get("post_install"):
        lines.append("")

    lines.append("echo '✅ Done! Installation complete.'")
    return "\n".join(lines)

# ─────────────────────────────────────────────────────────
#  SSH AUTO-INSTALLER
# ─────────────────────────────────────────────────────────
def ssh_install(ip, username, password, software_key, config):
    """
    SSH into the target machine and run install commands.
    Returns (success: bool, log: str)
    """
    sw = config["software"][software_key]
    all_commands = (
        sw.get("pre_install", []) +
        sw["commands"] +
        sw.get("post_install", [])
    )
    log_lines = []
    try:
        client = paramiko.SSHClient()
        client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        client.connect(ip, username=username, password=password, timeout=15)

        for cmd in all_commands:
            log_lines.append(f"$ {cmd}")
            _, stdout, stderr = client.exec_command(cmd, get_pty=True)
            out = stdout.read().decode(errors="replace").strip()
            err = stderr.read().decode(errors="replace").strip()
            if out:
                log_lines.append(out)
            if err and "warning" not in err.lower():
                log_lines.append(f"[stderr] {err}")
            log_lines.append("")

        client.close()
        return True, "\n".join(log_lines)
    except Exception as e:
        return False, str(e)

# ─────────────────────────────────────────────────────────
#  SESSION HELPERS
# ─────────────────────────────────────────────────────────
def init_session():
    """Reset the conversation to the beginning."""
    session["state"]    = "ask_name"
    session["name"]     = ""
    session["software"] = ""
    session["method"]   = ""
    session["ip"]       = ""
    session["username"] = ""
    session["password"] = ""
    session["script"]   = ""

# ─────────────────────────────────────────────────────────
#  MAIN STATE MACHINE
#  ─────────────────────────────────────────────────────────
#  States (in order):
#    ask_name → ask_software → ask_method
#      → (manual) → done
#      → (auto) → ask_ip → ask_username → ask_password → done
#
#  To ADD A NEW STEP in future, just add a new state here
#  and handle it below. The config.json controls software list.
# ─────────────────────────────────────────────────────────
def process_message(user_msg: str) -> dict:
    config   = load_config()
    state    = session.get("state", "ask_name")
    user_msg = user_msg.strip()

    # ── STATE: ask_name ──────────────────────────────────
    if state == "ask_name":
        name = user_msg.title()
        session["name"]  = name
        session["state"] = "ask_software"

        sw_list = "\n".join(
            f"{i+1}. {v['display_name']} — {v['description']}"
            for i, (_, v) in enumerate(config["software"].items())
        )
        reply = (
            f"Nice to meet you, {name}! 👋\n\n"
            f"Here is the list of some available software:\n\n"
            f"{sw_list}\n\n"
            f"Please type the number or the name of the software you need."
        )
        return {"reply": reply, "type": "text"}

    # ── STATE: ask_software ──────────────────────────────
    if state == "ask_software":
        sw_keys  = list(config["software"].keys())
        sw_names = [v["display_name"].lower() for v in config["software"].values()]
        chosen   = None

        if user_msg.isdigit():
            idx = int(user_msg) - 1
            if 0 <= idx < len(sw_keys):
                chosen = sw_keys[idx]
        else:
            for i, name in enumerate(sw_names):
                if user_msg.lower() in name:
                    chosen = sw_keys[i]
                    break

        if not chosen:
            sw_list = "\n".join(
                f"{i+1}. {v['display_name']}"
                for i, (_, v) in enumerate(config["software"].items())
            )
            return {
                "reply": f"Sorry, I did not recognise that. Please type the number from the list:\n\n{sw_list}",
                "type": "text",
            }

        session["software"] = chosen
        session["state"]    = "ask_method"
        sw_name = config["software"][chosen]["display_name"]

        reply = (
            f"You selected: **{sw_name}** ✅\n\n"
            f"How would you like to proceed?\n\n"
            f"**1.** 📄 Send me the **.sh script** — I will run it myself\n"
            f"**2.** 🤖 **Install automatically** — Connect to my machine via SSH(Only if you are available in office or connected via Daffodil VPN\n\n"
            f"Please type **1** or **2**."
        )
        return {"reply": reply, "type": "text"}

    # ── STATE: ask_method ────────────────────────────────
    if state == "ask_method":
        is_manual = "1" in user_msg or any(w in user_msg.lower() for w in ["script", "sh", "manual", "file"])
        is_auto   = "2" in user_msg or any(w in user_msg.lower() for w in ["auto", "ssh", "install", "connect"])

        if is_manual:
            session["method"] = "manual"
            session["state"]  = "done"
            script_text = make_sh_script(session["software"], config)
            session["script"] = script_text
            sw_name = config["software"][session["software"]]["display_name"]
            fname   = f"install_{session['software']}.sh"
            reply = (
                f"Here is your installation script for **{sw_name}**! 🎉\n\n"
                f"**Steps to use it:**\n"
                f"1. Click the download button below to save the file\n"
                f"2. Copy the file to your Ubuntu machine\n"
                f"3. Open a terminal and run these two commands:\n\n"
                f"   `chmod +x {fname}`\n"
                f"   `sudo ./{fname}`\n\n"
                f"That's it! Let me know if you need anything else."
            )
            return {"reply": reply, "type": "download", "filename": fname}

        elif is_auto:
            session["method"] = "auto"
            session["state"]  = "ask_ip"
            
            reply = (
                "I will install it automatically via SSH. 🔐\n\n"
    
                "⚠️ Before proceeding, To make sure SSH is installed and enabled on your machine.\n\n"
    
                "**Run the below commands:**\n"
                "`sudo systemctl enable ssh && sudo systemctl start ssh`\n\n"
                "→ Check firewall: `sudo ufw allow ssh`\n\n"
    
                "⚠️For SSH access your credentials are only used for this session and are **never saved**.\n\n"
    
                "Please enter the **IP address** of your Ubuntu machine\n"
                "you can find via the IP Address by ifconfig or ip a CMD"
                "(example: `172.18.*.*` or `10.0.*.*`):"
        )
        return {"reply": reply, "type": "text"}
       

    # ── STATE: ask_ip ────────────────────────────────────
    if state == "ask_ip":
        if not re.match(r"^\d{1,3}(\.\d{1,3}){3}$", user_msg):
            return {
                "reply": "That does not look like a valid IP address.\nPlease enter it in this format: `192.168.1.100`",
                "type": "text",
            }
        session["ip"]    = user_msg
        session["state"] = "ask_username"
        return {"reply": f"IP address saved: `{user_msg}` ✅\n\nNow please enter the **SSH username** (e.g. `ubuntu`, `admin`, `root`):", "type": "text"}

    # ── STATE: ask_username ──────────────────────────────
    if state == "ask_username":
        session["username"] = user_msg
        session["state"]    = "ask_password"
        return {
            "reply": f"Username: **{user_msg}** ✅\n\nNow please enter the **SSH password**:",
            "type": "text",
            "password_input": True,   # tells the UI to use a password field
        }

    # ── STATE: ask_password ──────────────────────────────
    if state == "ask_password":
        session["password"] = user_msg
        session["state"]    = "installing"
        sw_name = config["software"][session["software"]]["display_name"]

        # Run the installation
        success, log = ssh_install(
            session["ip"],
            session["username"],
            session["password"],
            session["software"],
            config,
        )
        session["state"] = "done"

        if success:
            reply = (
                f"✅ **{sw_name}** has been installed successfully on `{session['ip']}`!\n\n"
                f"**Installation log:**\n```\n{log[:3000]}\n```\n\n"
                f"All done, {session['name']}! Need anything else? Just say **restart** to start over."
            )
            return {"reply": reply, "type": "result", "success": True}
        else:
            reply = (
                f"❌ **Installation failed.**\n\n"
                f"**Error details:**\n```\n{log}\n```\n\n"
                f"Please check:\n"
                f"- Is the IP address correct? (`{session['ip']}`)\n"
                f"- Is SSH enabled on the machine?\n"
                f"- Is the username/password correct?\n\n"
                f"Type **restart** to try again."
            )
            return {"reply": reply, "type": "result", "success": False}

    # ── STATE: done ──────────────────────────────────────
    if state == "done":
        if "restart" in user_msg.lower() or "yes" in user_msg.lower() or "more" in user_msg.lower():
            init_session()
            return {"reply": "Let's start fresh! 😊 What is your name?", "type": "text"}
        return {
            "reply": "Your request is complete. Type **restart** if you need to install something else.",
            "type": "text",
        }

    # Fallback
    return {"reply": "Something went wrong. Please refresh the page.", "type": "text"}

# ─────────────────────────────────────────────────────────
#  FLASK ROUTES
# ─────────────────────────────────────────────────────────
@app.route("/")
def index():
    """Serve the chat page."""
    if "state" not in session:
        init_session()
    return HTML_PAGE

@app.route("/chat", methods=["POST"])
def chat():
    """Handle incoming chat messages."""
    if "state" not in session:
        init_session()
    data     = request.get_json()
    user_msg = data.get("message", "").strip()
    if not user_msg:
        return jsonify({"reply": "Please type a message.", "type": "text"})
    result = process_message(user_msg)
    return jsonify(result)

@app.route("/download")
def download():
    """Download the generated .sh script."""
    script   = session.get("script", "")
    filename = request.args.get("name", "install.sh")
    if not script:
        return "No script available.", 404
    buf = io.BytesIO(script.encode("utf-8"))
    buf.seek(0)
    return send_file(buf, as_attachment=True, download_name=filename, mimetype="text/plain")

@app.route("/reset")
def reset():
    """Reset the session."""
    init_session()
    return jsonify({"ok": True})

# ─────────────────────────────────────────────────────────
#  HTML PAGE  (terminal-style dark UI)
# ─────────────────────────────────────────────────────────
HTML_PAGE = r"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>IT Install Agent</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600&family=Inter:wght@400;500;600&display=swap');

    :root {
      --bg:       #0d1117;
      --surface:  #161b22;
      --border:   #30363d;
      --green:    #3fb950;
      --cyan:     #58a6ff;
      --yellow:   #d29922;
      --red:      #f85149;
      --text:     #e6edf3;
      --muted:    #8b949e;
      --user-bg:  #1f2b3e;
      --bot-bg:   #1a2332;
    }

    * { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      background: var(--bg);
      color: var(--text);
      font-family: 'Inter', sans-serif;
      height: 100vh;
      display: flex;
      flex-direction: column;
      overflow: hidden;
    }

    /* ── Header ── */
    header {
      display: flex;
      align-items: center;
      gap: 12px;
      padding: 14px 24px;
      border-bottom: 1px solid var(--border);
      background: var(--surface);
      flex-shrink: 0;
    }
    .header-dot { width: 10px; height: 10px; border-radius: 50%; background: var(--green); animation: pulse 2s infinite; }
    @keyframes pulse { 0%,100%{opacity:1} 50%{opacity:.4} }
    header h1 { font-family: 'JetBrains Mono', monospace; font-size: 15px; color: var(--green); letter-spacing: 1px; }
    header span { font-size: 12px; color: var(--muted); margin-left: auto; font-family: 'JetBrains Mono', monospace; }

    /* ── Chat area ── */
    #chat {
      flex: 1;
      overflow-y: auto;
      padding: 24px;
      display: flex;
      flex-direction: column;
      gap: 16px;
      scroll-behavior: smooth;
    }
    #chat::-webkit-scrollbar { width: 6px; }
    #chat::-webkit-scrollbar-track { background: var(--bg); }
    #chat::-webkit-scrollbar-thumb { background: var(--border); border-radius: 3px; }

    /* ── Messages ── */
    .msg { max-width: 78%; display: flex; flex-direction: column; gap: 4px; animation: fadeUp .25s ease; }
    @keyframes fadeUp { from{opacity:0;transform:translateY(8px)} to{opacity:1;transform:translateY(0)} }

    .msg.bot  { align-self: flex-start; }
    .msg.user { align-self: flex-end; }

    .msg-label { font-size: 11px; color: var(--muted); font-family: 'JetBrains Mono', monospace; padding: 0 4px; }
    .msg.bot  .msg-label { color: var(--cyan); }
    .msg.user .msg-label { text-align: right; color: var(--yellow); }

    .bubble {
      padding: 12px 16px;
      border-radius: 10px;
      font-size: 14px;
      line-height: 1.65;
      white-space: pre-wrap;
      word-break: break-word;
    }
    .msg.bot  .bubble { background: var(--bot-bg); border: 1px solid var(--border); border-top-left-radius: 3px; }
    .msg.user .bubble { background: var(--user-bg); border: 1px solid #2d4a70; border-top-right-radius: 3px; }

    /* Inline code */
    .bubble code {
      font-family: 'JetBrains Mono', monospace;
      background: rgba(255,255,255,.07);
      padding: 2px 6px;
      border-radius: 4px;
      font-size: 12.5px;
      color: var(--cyan);
    }
    /* Code blocks */
    .bubble pre {
      background: #0d1117;
      border: 1px solid var(--border);
      border-radius: 8px;
      padding: 12px;
      overflow-x: auto;
      margin-top: 8px;
      font-family: 'JetBrains Mono', monospace;
      font-size: 12px;
      color: #c9d1d9;
    }
    /* Bold */
    .bubble strong { color: #fff; font-weight: 600; }

    /* Download button */
    .dl-btn {
      display: inline-flex;
      align-items: center;
      gap: 8px;
      margin-top: 10px;
      padding: 9px 18px;
      background: var(--green);
      color: #000;
      font-weight: 600;
      font-size: 13px;
      border-radius: 7px;
      text-decoration: none;
      transition: opacity .15s;
    }
    .dl-btn:hover { opacity: .85; }

    /* Typing indicator */
    .typing .bubble { padding: 14px 18px; }
    .dots span {
      display: inline-block;
      width: 7px; height: 7px;
      background: var(--muted);
      border-radius: 50%;
      margin: 0 2px;
      animation: bounce .9s infinite;
    }
    .dots span:nth-child(2){ animation-delay:.15s }
    .dots span:nth-child(3){ animation-delay:.3s }
    @keyframes bounce { 0%,60%,100%{transform:translateY(0)} 30%{transform:translateY(-6px)} }

    /* ── Input area ── */
    footer {
      padding: 16px 24px;
      background: var(--surface);
      border-top: 1px solid var(--border);
      flex-shrink: 0;
    }
    .input-row {
      display: flex;
      gap: 10px;
      align-items: flex-end;
    }
    #input-box {
      flex: 1;
      background: var(--bg);
      border: 1px solid var(--border);
      color: var(--text);
      font-family: 'JetBrains Mono', monospace;
      font-size: 14px;
      padding: 12px 16px;
      border-radius: 8px;
      outline: none;
      resize: none;
      min-height: 46px;
      max-height: 120px;
      transition: border-color .2s;
    }
    #input-box:focus { border-color: var(--cyan); }
    #input-box::placeholder { color: var(--muted); }

    #send-btn {
      padding: 12px 22px;
      background: var(--cyan);
      color: #000;
      font-weight: 700;
      font-size: 13px;
      border: none;
      border-radius: 8px;
      cursor: pointer;
      transition: opacity .15s;
      white-space: nowrap;
    }
    #send-btn:hover { opacity: .85; }
    #send-btn:disabled { opacity: .4; cursor: default; }

    .hint { font-size: 11px; color: var(--muted); margin-top: 8px; font-family: 'JetBrains Mono', monospace; }
  </style>
</head>
<body>

<header>
  <div class="header-dot"></div>
  <h1>IT INSTALL AGENT</h1>
  <span>Powered by Ollama · Secure · Local</span>
</header>

<div id="chat"></div>

<footer>
  <div class="input-row">
    <textarea id="input-box" placeholder="Type your message here..." rows="1"></textarea>
    <button id="send-btn" onclick="sendMsg()">Send ↵</button>
  </div>
  <div class="hint">Press Enter to send · Shift+Enter for new line</div>
</footer>

<script>
  let passwordMode = false;
  let downloadFile = null;

  const chat   = document.getElementById("chat");
  const input  = document.getElementById("input-box");
  const sendBtn = document.getElementById("send-btn");

  // Auto-resize textarea
  input.addEventListener("input", () => {
    input.style.height = "auto";
    input.style.height = Math.min(input.scrollHeight, 120) + "px";
  });

  // Enter to send
  input.addEventListener("keydown", (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      sendMsg();
    }
  });

  function addMessage(role, text, extra) {
    const div = document.createElement("div");
    div.className = "msg " + role;

    const label = document.createElement("div");
    label.className = "msg-label";
    label.textContent = role === "bot" ? "🤖 IT Agent" : "👤 You";
    div.appendChild(label);

    const bubble = document.createElement("div");
    bubble.className = "bubble";
    bubble.innerHTML = formatText(text);

    // Append download button if provided
    if (extra && extra.type === "download" && extra.filename) {
      const btn = document.createElement("a");
      btn.className = "dl-btn";
      btn.href = "/download?name=" + encodeURIComponent(extra.filename);
      btn.download = extra.filename;
      btn.innerHTML = "⬇ Download " + extra.filename;
      bubble.appendChild(btn);
    }

    div.appendChild(bubble);
    chat.appendChild(div);
    chat.scrollTop = chat.scrollHeight;
  }

  function addTyping() {
    const div = document.createElement("div");
    div.className = "msg bot typing";
    div.id = "typing-indicator";
    div.innerHTML = '<div class="msg-label">🤖 IT Agent</div><div class="bubble"><div class="dots"><span></span><span></span><span></span></div></div>';
    chat.appendChild(div);
    chat.scrollTop = chat.scrollHeight;
  }

  function removeTyping() {
    const t = document.getElementById("typing-indicator");
    if (t) t.remove();
  }

  function formatText(text) {
  // Bold
  text = text.replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>");

  // Inline code
  text = text.replace(/`([^`\n]+)`/g, "<code>$1</code>");

  // Code blocks (FIXED)
  text = text.replace(/```([\s\S]*?)```/gm, function(match, code) {
    return "<pre>" + escHtml(code.trim()) + "</pre>";
  });

  return text;
}

  function escHtml(str) {
    return str.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
  }

  async function sendMsg() {
    const msg = input.value.trim();
    if (!msg) return;

    // Show what user typed (mask password)
    addMessage("user", passwordMode ? "••••••••" : msg);
    input.value = "";
    input.style.height = "auto";
    sendBtn.disabled = true;

    addTyping();
    try {
      const resp = await fetch("/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ message: msg }),
      });
      const data = await resp.json();
      removeTyping();

      // Update password mode for next input
      passwordMode = data.password_input === true;
      input.type = passwordMode ? "password" : "text";

      addMessage("bot", data.reply, data);
    } catch (err) {
      removeTyping();
      addMessage("bot", "⚠️ Could not reach the server. Please check that the app is running.");
    }
    sendBtn.disabled = false;
    input.focus();
  }

  // Start the conversation on page load
  window.onload = async () => {
    addTyping();
    try {
      const resp = await fetch("/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ message: "__start__" }),
      });
      // We need to handle the first message specially
    } catch(e) {}
    removeTyping();
    // Send a silent start trigger
    await fetch("/reset");
    addMessage("bot", "👋 Hello! I am your IT Software Install Agent.\\n\\nI can help you install approved software on Ubuntu machines.\\n\\nTo get started — what is your **name**?");
    input.focus();
  };
</script>
</body>
</html>
"""

# ─────────────────────────────────────────────────────────
#  RUN
# ─────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("=" * 55)
    print("  IT Install Agent is running!")
    print("  Open your browser: http://localhost:5000")
    print("=" * 55)
    app.run(debug=True, host="0.0.0.0", port=5000)
